### ISSUE TITLE
CONFIG_FEATURE_TAR_OLDGNU_COMPATIBILITY for busybox

### ISSUE THREAD

**Issue by ysangkok** [radial/core-busyboxplus#3]
It is not possible to extract make-4.1.tar.{gz,bz2} using the shipped busybox. GNU tar can extract it. I suspect is it due to this config option.

Thanks in advance.

**Comment by clemtibs** [comment]
seems easy enough to add to the images. I'll have to test it a bit later though. Curious what your exact error message was?

**Comment by ysangkok** [comment]
Here's another file with the same problem, 

```
janus@zeus /tmp % curl -sL http://sourceforge.net/projects/libuuid/files/libuuid-1.0.3.tar.gz/download | gunzip | busybox tar t
tar: invalid tar magic
janus@zeus /tmp %
```

This is using the default busybox on Ubuntu 14.10 (utopic), which apparently has the same problem. GNU tar works. I also patched `sltar`, it can easily be made to work.

**Comment by ysangkok** [comment]
Closing since I stopped using busybox.
